### PR TITLE
Removed all redundant pieces of code. 

### PR DESCRIPTION
**Pull request by Michael2109**
Also updated code in cobalt file to the correct syntax while doing this.

### CODE REVIEW

**Review by FilipJanitor — COMMENTED** [review]
Maybe the unused test modules in compiler/test/tests/cobalt/parsers/ParserTests.h need not to be removed, just commented out (yeah, commiting commented code is not the best thing...) - the reasoning is, that after implementing those modules one will surely not break the alphabetical order of imports.  But I am not sure what is the better option. Except this all looks good!

**Comment by Michael2109** [comment]
I feel it is a bit nicer to remove all messages of unused code for now. Means that if we add new unused code pieces we will instantly notice it. 
Shouldn't be too difficult adding the imports etc in later instead I think.

**Comment by FilipJanitor** [comment]
Yeah, but if it were commented it would not throw the warnings. Ok, we will keep it clean.

**Review by FilipJanitor — APPROVED** [review]

**Comment by Michael2109** [comment]
Sorry I missed you said to comment it out. I think it could be better to try and keep the master branch clean if we can.

**Pull request merged**
