### PR TITLE
Cobalt 437

### PR DESCRIPTION
**Pull request by Michael2109**
Added match parser.

### CODE REVIEW

**Comment by FilipJanitor** [comment]
Just one little thing - what is the purpose of wrapping the cases in assignment data? In the do one it is even wrapped twice - `StmtAssignment . BlockStmt`

**Comment by Michael2109** [comment]
Isn't this required? It could either be an expression or a statement depending on whether it is inline or not. We wrap it in this like in method definitions to allow for both cases.

**Comment by FilipJanitor** [comment]
I understand what you mean and the similarity between those two usages, but still, even the name suggests that the data has something to with assignments which might not be the case for patternmatching. I am not sure, whether to wrap the inline one into `ExprAsStmt` or rename the data to some more general name that would suggest, that its purpose is to distinguish between inline and block stuff (which does not necessarly imply assignment context)

**Comment by FilipJanitor** [comment]
A workaround from java community for recursive traversal.
```
javac $(find ./rootdir/* | grep .java)
```
This works only for Linux or Unix systems. They suggest using build tools to manage file hierarchies.

**Comment by Michael2109** [comment]
I think the usages are very similar so renaming it sounds best to me. Will need to think of something.

**Comment by Michael2109** [comment]
I'm a bit unsure of what to call this. We could call it `Value` or something. I'm struggling to think of a word for it.

**Comment by FilipJanitor** [comment]
It is tough decision. How about something like `InlineDoBlock`? That might be confusing too

**Comment by Michael2109** [comment]
Okay how about `Block`, with `Inline` and `DoBlock`? That might be okay?

**Comment by FilipJanitor** [comment]
That sounds good.

**Comment by Michael2109** [comment]
All looks to be working fine. My tests are passing. There seems to be tests failing on the build server with the master branch at the moment that I need to look into.

**Review by FilipJanitor — APPROVED** [review]

**Comment by FilipJanitor** [comment]
Sorry, my VM clock got crazy so that is why my commit looks from the past. Tests seem to pass, all looks great.

**Comment by Michael2109** [comment]
I'm going to merge this ignoring the failing build as it is a separate issue.

**Pull request merged**
