### PR TITLE
Cobalt 393

### PR DESCRIPTION
**Pull request by Michael2109**
Changed module names to match the directory structure.

### CODE REVIEW

**Review by FilipJanitor — COMMENTED** [review]
According to [style guide](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md) module names should be singular.

**Comment by Michael2109** [comment]
That makes sense. Okay will update it.

**Comment by Michael2109** [comment]
Which cases are you referring to? ParserTests, IntegrationTests and UtilsTests?

**Comment by FilipJanitor** [comment]
Yeah, those and also Parsers and Utils please.

**Comment by Michael2109** [comment]
In the case of ParserTests, IntegrationTests, and UtilsTests what would be a good alternative? The thing with these is they contain all of the tests to keep things organised so calling it `test` wouldn't quite be right.

**Comment by FilipJanitor** [comment]
After checking some repos it seems that the naming convention on test modules is not used so strictly. Maybe we dont need to rename them after all and just rename the library modules. Sorry for causing this confusion.

**Comment by Michael2109** [comment]
I've done it now anyway besides them last cases I mentioned.  I think just for them cases we can ignore it.

**Review by FilipJanitor — APPROVED** [review]

**Pull request merged**
