### PR TITLE
Cobalt 486

### PR DESCRIPTION
**Pull request by Michael2109**
Added compiling of a whole directory in testing. 
Although we may want to change this in the future this will be very useful for the moment. It will allow for us to progress with code generation. We can add another issue related to other methods of how we should compile directories.

### CODE REVIEW

**Comment by FilipJanitor** [comment]
I am not entirely sure about usage of this. How would the command for compilation look to utilize this feature? Because currently (on Linux)  when I have a directory with more .cobalt files and I use `stack exec compiler-exe -- *.cobalt` all the files are compiled. Bash does all the work with patternmatching etc. and feeds a list of files to the compiler.

**Comment by Michael2109** [comment]
I see what you mean. Okay I'll try changing it to this. 
I realise now it was rather pointless what I was doing.

**Comment by FilipJanitor** [comment]
On the other hand, this might be used when testing. I don't know how the integration tests are going to work. If there is no shell step in the process, there is no other way to test compiling multiple files elegantly (without enumerating all of them) other than making the compiler compile a directory. Also the simple wildcard way does not work for subdirectories, other tricks need to be used for traversing them.

**Comment by Michael2109** [comment]
I was wondering if it would work recursively. If we could get something to work recursive then this was is perfect. 
The integration tests have a `shell` step. I am running command line commands to execute everything so it is possible.

**Comment by FilipJanitor** [comment]
Sorry - wrong thread. Java workaround for Unix and Linux:
```
javac $(find ./rootdir/* | grep .java)
```
Java people suggest using build tools to manage file hierarchies.

**Comment by Michael2109** [comment]
Can we do any of this cross platform? 
In this context what do you mean by build tools?

**Comment by FilipJanitor** [comment]
There probably are ways but it is a bit unpractical https://stackoverflow.com/a/6285197/7378363
I meant like Ant or Maven. I dont know many people compiling java by hand. I believe most of the time some IDE is used for development and building is managed in the background by these build tools.

**Comment by Michael2109** [comment]
In our case build tools are things that would use the compiler but not the other way around. 
Either way we need a test utils function that will automatically compile a whole directory. If it can't be done command line cross platform then the method I've used is probably best?

**Comment by FilipJanitor** [comment]
Yeah sure, the build tool has no problem enumerating all the files when using the compiler. You are right- if the usecase is testing then you are right - there is no other way around.

**Review by FilipJanitor — APPROVED** [review]

**Comment by FilipJanitor** [comment]
But still, what do you think about using a commandline argument for compiling directories? If I understand - currently the arguments can be either directories or files.

**Comment by Michael2109** [comment]
Sounds like a good idea to me. Feel free to create a new issue for it.

**Pull request merged**
