### PR TITLE
add import parser tests

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Comment by Michael2109** [comment]
Hi Matt,
Just a small thing. Would it be possible to name the tests in this format `testImportExampleName`?
This means you can then add all import related tests in alphabetical order in the `ParserTests` module. When we have many tests it will be easier to look through and find the ones for particular parsers etc.    
Also I was thinking it could be useful having a few more tests for these cases. What do you think about something like this? 

Failures:
`import dir.subdir.123Name`
`import 1Name`

Passes:
`import dir.subdir.ClassName`
`import dir.sub_dir.ClassName`
`import dir.sub_dir.Class_Name`
`import dir.sub_dir.ClassName123`

**Comment by mlutze** [comment]
Makes sense. Is there somewhere I should be looking for specifications? Looking at the code might only lead to affirmative tests rather than ones that find bugs.

**Comment by Michael2109** [comment]
I will be aiming to have written up a specification this week. There have been a lot of other issues I've been working on so I haven't gotten to it yet.

**Comment by Michael2109** [comment]
This all looks great thank you Matt.

**Pull request merged**
