### PR TITLE
add pure keyword

### PR DESCRIPTION
**Pull request by mlutze**

### CODE REVIEW

**Review by Michael2109 — COMMENTED** [review]
Could you also add a test for the model parser too?

**Review by Michael2109 — COMMENTED** [review]
Sorry I mean to test a model with the modifier. E.g. `pure class ClassName`. This will allow for specifying that a whole class/object is pure.

**Comment by mlutze** [comment]
Ah, that makes more sense, haha. I missed that part of the issue.

**Review by Michael2109 — APPROVED** [review]
This is great thanks!

**Pull request merged**
